from enum import Enum


class ProtocolCodes(Enum):
    LOGIN_REQUEST = "LGRQ"
    LOGIN_RESPONSE = "LGRS"
    SIGN_UP_REQUEST = "SNRQ"
    SIGN_UP_RESPONSE = "SNRS"
    FORGOT_PASSWORD_REQUEST = "FPRQ"
    FORGOT_PASSWORD_RESPONSE = "FPRS"
    VERIFY_SIGN_UP_REQUEST = "VSRQ"
    VERIFY_SIGN_UP_RESPONSE = "VSRS"
    RESEND_VERIFICATION_CODE_REQUEST = "RVRQ" #לייצר מחדש קוד אם נגמר הזמן של הקוד הקודם
    RESEND_VERIFICATION_CODE_RESPONSE = "RVRS"
